---
- name: 'Instalando pacotes..'
  apt:
    name: "{{item}}"
    state: latest
  become: yes
  with_items:
    - mysql-server-5.7
    - python-pymysql
- name: 'Criando o banco do wordpress no MySql'
  mysql_db:
    name: "{{wp_db_name}}"
    login_user: root
    login_password: root
    state: present
  become: yes
- name: 'Criando o usuário do banco do wordpress'
  mysql_user:
    login_user: root
    login_password: root
    name: "{{wp_username}}"
    password: "{{wp_user_password}}"
    priv: "{{wp_db_name}}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - "{{wp_host_ip}}" 
- name: 'Configura mysql para conexões de outros hosts'
  copy:
    src: 'files/mysqld.cnf'
    dest: '/etc/mysql/mysql.conf.d/mysqld.cnf'
  become: yes
  notify:
    - restart mysql